backend:
  name: github
  branch: main
  repo: leightonhughes/Vitepress-with-Decap-CMS
media_folder: "docs/public/media"
public_folder: "/media"
publish_mode: editorial_workflow
collections:
  - label: "Settings"
    name: "settings"
    files:
      - file: "docs/settings/navigation.yml"
        label: "Navigation"
        name: "navigation"
        fields:
          - label: "Navigation"
            name: "nav_items"
            widget: "list"
            fields:
              - { label: "Label", name: "label", widget: "string" }
              - { label: "Path", name: "path", widget: "string" }
  - label: "Post"
    name: "posts"
    folder: "docs/post"
    create: true
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Meta description", name: "description", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }