backend:
  name: github
  repo: leightonhughes/Vitepress-with-Decap-CMS
  branch: main
media_folder: "docs/public/media"
public_folder: "/media"
publish_mode: editorial_workflow
collections:
  - label: "Post"
    name: "posts"
    folder: "docs/post"
    summary: '{{title}} -- {{year}}/{{month}}/{{day}}'
    create: true
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: 'Publish Date', name: 'date', widget: 'datetime' }
      - { label: "Order", name: "order", widget: "string" }
      - { label: "Meta description", name: "description", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }