backend:
  name: git-gateway
  repo: catholicmelb/parish-handbook
  branch: main
media_folder: "docs/public/media"
public_folder: "/media"
publish_mode: editorial_workflow
collections:
  - label: "Contents"
    name: "contents"
    folder: "docs/contents"
    summary: '{{title}}'
    create: true
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: 'Publish Date', name: 'date', widget: 'datetime' }
      - { label: "Order in sidebar", name: "order", widget: "string" }
      - { label: "Meta description", name: "description", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }
  - label: "Pages"
    name: "pages"
    folder: "docs"
    summary: '{{title}}'
    create: true
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: 'Publish Date', name: 'date', widget: 'datetime' }
      - { label: "Meta description", name: "description", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }
