backend:
  name: github
  repo: leightonhughes/Vitepress-with-Decap-CMS
media_folder: "docs/public/media"
public_folder: "/media"
publish_mode: editorial_workflow
collections:
  - label: "Post"
    name: "posts"
    folder: "docs/post"
    create: true
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Meta description", name: "description", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }